# Generated by Django 4.1.2 on 2022-10-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Vuelo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aciento', models.CharField(max_length=255)),
                ('pasajero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reservacion.pasajero')),
                ('vuelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Vuelo.vuelo')),
            ],
        ),
    ]
