# Generated by Django 4.1.2 on 2022-10-31 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=500)),
                ('fecha', models.DateField()),
                ('ciudadDestino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadDestino_content_type', to='Vuelo.ciudad')),
                ('ciudadOrigen', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudadOrigen_content_type', to='Vuelo.ciudad')),
            ],
        ),
    ]
